// <auto-generated />
// Stage 5.3 iter-9 evaluator item 1 — provider-portable migration.
// The original iter-7/iter-8 emission of this migration hard-coded
// SQLite-shaped store types (`type: "TEXT"`, `type: "INTEGER"`)
// on every column. Those hints make EF generate raw `CREATE TABLE
// audit_logs (..., Timestamp INTEGER, ...)` on the target engine,
// which produces a 32-bit integer column on PostgreSQL / SQL Server
// (truncating the `long` Unix-ms timestamps) and is non-portable.
// The fix is to drop the explicit `type:` hints so EF Core picks
// provider-native types at migration apply time:
//   * SQLite — `Guid` -> `TEXT` (default GuidToStringConverter),
//     `long` -> `INTEGER`, `string` -> `TEXT (NVARCHAR(N))`.
//   * PostgreSQL — `Guid` -> `uuid`, `long` -> `bigint`,
//     `string` -> `character varying(N)`.
//   * SQL Server — `Guid` -> `uniqueidentifier`, `long` -> `bigint`,
//     `string` -> `nvarchar(N)`.
// All three providers honour the column-default + CHECK constraint
// expressions emitted below verbatim, so the migration runs unchanged
// across the provider matrix supported in
// ServiceCollectionExtensions.AddMessagingPersistence.
using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace AgentSwarm.Messaging.Persistence.Migrations.Audit
{
    /// <inheritdoc />
    public partial class InitialCreate : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "audit_logs",
                columns: table => new
                {
                    Id = table.Column<Guid>(nullable: false),
                    MessageId = table.Column<string>(maxLength: 128, nullable: true),
                    ExternalUserId = table.Column<string>(maxLength: 128, nullable: false),
                    AgentId = table.Column<string>(maxLength: 128, nullable: true),
                    Action = table.Column<string>(maxLength: 64, nullable: false),
                    EventFamily = table.Column<string>(maxLength: 32, nullable: false),
                    Timestamp = table.Column<long>(nullable: false),
                    CorrelationId = table.Column<string>(maxLength: 128, nullable: false),
                    TenantId = table.Column<string>(maxLength: 128, nullable: true),
                    Details = table.Column<string>(nullable: true),
                    Platform = table.Column<string>(maxLength: 32, nullable: false, defaultValue: "Telegram"),
                    EntryKind = table.Column<string>(maxLength: 32, nullable: false),
                    QuestionId = table.Column<string>(maxLength: 128, nullable: true),
                    ActionValue = table.Column<string>(maxLength: 64, nullable: true),
                    Comment = table.Column<string>(nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_audit_logs", x => x.Id);
                    // Stage 5.3 iter-8 evaluator item 2 — DB-level
                    // CHECK constraint pinning `Platform = 'Telegram'`.
                    // The model-side guard in AuditDbContext stops
                    // EF-tracked Adds; this CHECK is the engine-level
                    // line of defence that catches raw-SQL inserts,
                    // bulk-insert tools, and any future client that
                    // bypasses the EF model. Emitted inline on the
                    // bootstrap migration (rather than as a separate
                    // ALTER) so a freshly-created audit DB carries the
                    // constraint from row zero and so SQLite — which
                    // does not support ALTER TABLE ADD CONSTRAINT —
                    // gets the CHECK without a table-rebuild migration.
                    // The double-quoted identifier `"Platform"` is
                    // honoured by all three providers (SQLite always,
                    // PostgreSQL always, SQL Server when
                    // QUOTED_IDENTIFIER is ON which is the EF default).
                    table.CheckConstraint(
                        "ck_audit_logs_platform_telegram",
                        "\"Platform\" = 'Telegram'");
                });

            migrationBuilder.CreateIndex(
                name: "ix_audit_logs_correlation_id",
                table: "audit_logs",
                column: "CorrelationId");

            migrationBuilder.CreateIndex(
                name: "ix_audit_logs_external_user_id",
                table: "audit_logs",
                column: "ExternalUserId");

            migrationBuilder.CreateIndex(
                name: "ix_audit_logs_timestamp",
                table: "audit_logs",
                column: "Timestamp");

            migrationBuilder.CreateIndex(
                name: "ix_audit_logs_event_family",
                table: "audit_logs",
                column: "EventFamily");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "audit_logs");
        }
    }
}
