// <auto-generated />
// Stage 5.3 iter-9 evaluator item 1 — provider-portable snapshot.
// The HasColumnType("TEXT")/("INTEGER") hints emitted by the iter-7
// SQLite design-time scaffolder were stripped so the snapshot stays
// in sync with the now-provider-agnostic OnModelCreating + migration
// Up() method. A future `dotnet ef migrations add` invocation against
// any of the three supported providers (SQLite, PostgreSQL, SQL
// Server) will see a clean diff rather than emitting an AlterColumn
// to switch column types on every scaffold.
using System;
using AgentSwarm.Messaging.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AgentSwarm.Messaging.Persistence.Migrations.Audit
{
    [DbContext(typeof(AuditDbContext))]
    partial class AuditDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.27");

            modelBuilder.Entity("AgentSwarm.Messaging.Persistence.AuditLogEntry", b =>
                {
                    b.Property<Guid>("Id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(64);

                    b.Property<string>("ActionValue")
                        .HasMaxLength(64);

                    b.Property<string>("AgentId")
                        .HasMaxLength(128);

                    b.Property<string>("Comment");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(128);

                    b.Property<string>("Details");

                    b.Property<string>("EntryKind")
                        .IsRequired()
                        .HasMaxLength(32);

                    b.Property<string>("EventFamily")
                        .IsRequired()
                        .HasMaxLength(32);

                    b.Property<string>("ExternalUserId")
                        .IsRequired()
                        .HasMaxLength(128);

                    b.Property<string>("MessageId")
                        .HasMaxLength(128);

                    b.Property<string>("Platform")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasDefaultValue("Telegram");

                    b.Property<string>("QuestionId")
                        .HasMaxLength(128);

                    b.Property<string>("TenantId")
                        .HasMaxLength(128);

                    b.Property<long>("Timestamp");

                    b.HasKey("Id");

                    b.HasIndex("CorrelationId")
                        .HasDatabaseName("ix_audit_logs_correlation_id");

                    b.HasIndex("EventFamily")
                        .HasDatabaseName("ix_audit_logs_event_family");

                    b.HasIndex("ExternalUserId")
                        .HasDatabaseName("ix_audit_logs_external_user_id");

                    b.HasIndex("Timestamp")
                        .HasDatabaseName("ix_audit_logs_timestamp");

                    b.ToTable("audit_logs", null, t =>
                        {
                            t.HasCheckConstraint("ck_audit_logs_platform_telegram", "\"Platform\" = 'Telegram'");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
