// <auto-generated />
using System;
using AgentSwarm.Messaging.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AgentSwarm.Messaging.Persistence.Migrations
{
    [DbContext(typeof(MessagingDbContext))]
    [Migration("20260516042511_Discord_InitialCreate")]
    partial class Discord_InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.13");

            modelBuilder.Entity("AgentSwarm.Messaging.Abstractions.GuildBinding", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AllowedRoleIds")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("ChannelId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChannelPurpose")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CommandRestrictions")
                        .HasColumnType("TEXT");

                    b.Property<long>("GuildId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("RegisteredAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkspaceId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GuildId", "ChannelPurpose")
                        .HasDatabaseName("IX_GuildBindings_Guild_Purpose");

                    b.HasIndex("GuildId", "ChannelId", "WorkspaceId")
                        .IsUnique()
                        .HasDatabaseName("IX_GuildBindings_Guild_Channel_Workspace_Unique");

                    b.ToTable("GuildBindings", (string)null);
                });

            modelBuilder.Entity("AgentSwarm.Messaging.Abstractions.OutboundMessage", b =>
                {
                    b.Property<Guid>("MessageId")
                        .HasColumnType("TEXT");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ChatId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ErrorDetail")
                        .HasColumnType("TEXT");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxAttempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(5);

                    b.Property<DateTimeOffset?>("NextRetryAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("PlatformMessageId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("SentAt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Severity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceEnvelopeJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceId")
                        .HasColumnType("TEXT");

                    b.Property<int>("SourceType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("MessageId");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("IX_OutboundMessages_IdempotencyKey_Unique");

                    b.HasIndex("Status", "Severity", "NextRetryAt")
                        .HasDatabaseName("IX_OutboundMessages_Status_Severity_NextRetryAt");

                    b.ToTable("OutboundMessages", (string)null);
                });

            modelBuilder.Entity("AgentSwarm.Messaging.Persistence.AuditLogEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalUserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MessageId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CorrelationId")
                        .HasDatabaseName("IX_AuditLog_CorrelationId");

                    b.HasIndex("Platform", "Timestamp")
                        .HasDatabaseName("IX_AuditLog_Platform_Timestamp");

                    b.ToTable("AuditLog", (string)null);
                });

            modelBuilder.Entity("AgentSwarm.Messaging.Persistence.DeadLetterMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ChatId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ErrorReason")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("FailedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OriginalMessageId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OriginalMessageId")
                        .IsUnique()
                        .HasDatabaseName("IX_DeadLetterMessages_OriginalMessageId_Unique");

                    b.ToTable("DeadLetterMessages", (string)null);
                });

            modelBuilder.Entity("AgentSwarm.Messaging.Persistence.DiscordInteractionRecord", b =>
                {
                    b.Property<long>("InteractionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AttemptCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<long>("ChannelId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ErrorDetail")
                        .HasColumnType("TEXT");

                    b.Property<long>("GuildId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdempotencyStatus")
                        .HasColumnType("INTEGER");

                    b.Property<int>("InteractionType")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("RawPayload")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("InteractionId");

                    b.HasIndex("InteractionId")
                        .IsUnique()
                        .HasDatabaseName("IX_DiscordInteractions_InteractionId_Unique");

                    b.HasIndex("IdempotencyStatus", "ReceivedAt")
                        .HasDatabaseName("IX_DiscordInteractions_Status_ReceivedAt");

                    b.ToTable("DiscordInteractions", (string)null);
                });

            modelBuilder.Entity("AgentSwarm.Messaging.Persistence.PendingQuestionRecord", b =>
                {
                    b.Property<string>("QuestionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("AgentQuestion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultActionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultActionValue")
                        .HasColumnType("TEXT");

                    b.Property<long>("DiscordChannelId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("DiscordMessageId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("DiscordThreadId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<long?>("RespondentUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SelectedActionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SelectedActionValue")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("StoredAt")
                        .HasColumnType("TEXT");

                    b.HasKey("QuestionId");

                    b.HasIndex("DiscordChannelId", "DiscordMessageId")
                        .HasDatabaseName("IX_PendingQuestions_Channel_Message");

                    b.HasIndex("Status", "ExpiresAt")
                        .HasDatabaseName("IX_PendingQuestions_Status_ExpiresAt");

                    b.ToTable("PendingQuestions", (string)null);
                });

            modelBuilder.Entity("AgentSwarm.Messaging.Persistence.DeadLetterMessage", b =>
                {
                    b.HasOne("AgentSwarm.Messaging.Abstractions.OutboundMessage", null)
                        .WithOne()
                        .HasForeignKey("AgentSwarm.Messaging.Persistence.DeadLetterMessage", "OriginalMessageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
