// <auto-generated />
using AgentSwarm.Messaging.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AgentSwarm.Messaging.Persistence.Migrations
{
    [DbContext(typeof(MessagingDbContext))]
    [Migration("20260516000000_AddInboundProcessingStartedAt")]
    partial class AddInboundProcessingStartedAt
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.27");

            modelBuilder.Entity("AgentSwarm.Messaging.Abstractions.InboundUpdate", b =>
                {
                    b.Property<long>("UpdateId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AttemptCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorDetail")
                        .HasColumnType("TEXT");

                    b.Property<string>("HandlerErrorDetail")
                        .HasColumnType("TEXT");

                    b.Property<string>("IdempotencyStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<long?>("ProcessedAt")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ProcessingStartedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RawPayload")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("ReceivedAt")
                        .HasColumnType("INTEGER");

                    b.HasKey("UpdateId");

                    b.HasIndex("UpdateId")
                        .IsUnique()
                        .HasDatabaseName("ix_inbound_updates_update_id");

                    b.HasIndex("IdempotencyStatus", "AttemptCount")
                        .HasDatabaseName("ix_inbound_updates_status_attempt");

                    b.ToTable("inbound_updates", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
