// <auto-generated />
using System;
using AgentSwarm.Messaging.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AgentSwarm.Messaging.Persistence.Migrations
{
    [DbContext(typeof(MessagingDbContext))]
    partial class MessagingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.27");

            modelBuilder.Entity("AgentSwarm.Messaging.Abstractions.DeadLetterMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AgentId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("AlertStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<long?>("AlertSentAt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AttemptTimestamps")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("[]");

                    b.Property<long>("ChatId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<long>("DeadLetteredAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ErrorHistory")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("[]");

                    b.Property<string>("FailureCategory")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("TEXT");

                    b.Property<string>("FinalError")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OriginalMessageId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ReplayCorrelationId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ReplayStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("None");

                    b.Property<int>("Severity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceEnvelopeJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CorrelationId")
                        .HasDatabaseName("ix_dead_letter_messages_correlation_id");

                    b.HasIndex("DeadLetteredAt")
                        .HasDatabaseName("ix_dead_letter_messages_dead_lettered_at");

                    b.HasIndex("OriginalMessageId")
                        .IsUnique()
                        .HasDatabaseName("ux_dead_letter_messages_original_message_id");

                    b.HasIndex("AlertStatus", "Severity")
                        .HasDatabaseName("ix_dead_letter_messages_alert_status_severity");

                    b.HasIndex("AgentId")
                        .HasDatabaseName("ix_dead_letter_messages_agent_id");

                    b.HasIndex("ReplayStatus")
                        .HasDatabaseName("ix_dead_letter_messages_replay_status");

                    b.ToTable("dead_letter_messages", (string)null);
                });

            modelBuilder.Entity("AgentSwarm.Messaging.Abstractions.InboundUpdate", b =>
                {
                    b.Property<long>("UpdateId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AttemptCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorDetail")
                        .HasColumnType("TEXT");

                    b.Property<string>("HandlerErrorDetail")
                        .HasColumnType("TEXT");

                    b.Property<string>("IdempotencyStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<long?>("ProcessedAt")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ProcessingStartedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RawPayload")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("ReceivedAt")
                        .HasColumnType("INTEGER");

                    b.HasKey("UpdateId");

                    b.HasIndex("UpdateId")
                        .IsUnique()
                        .HasDatabaseName("ix_inbound_updates_update_id");

                    b.HasIndex("IdempotencyStatus", "AttemptCount")
                        .HasDatabaseName("ix_inbound_updates_status_attempt");

                    b.ToTable("inbound_updates", (string)null);
                });

            modelBuilder.Entity("AgentSwarm.Messaging.Abstractions.OutboundDeadLetterRecord", b =>
                {
                    b.Property<Guid>("DeadLetterId")
                        .HasColumnType("TEXT");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ChatId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<long>("FailedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FailureCategory")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastErrorMessage")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastErrorType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("DeadLetterId");

                    b.HasIndex("ChatId")
                        .HasDatabaseName("ix_outbound_dlq_chat_id");

                    b.HasIndex("CorrelationId")
                        .HasDatabaseName("ix_outbound_dlq_correlation_id");

                    b.ToTable("outbound_dead_letters", (string)null);
                });

            modelBuilder.Entity("AgentSwarm.Messaging.Abstractions.OutboundMessage", b =>
                {
                    b.Property<Guid>("MessageId")
                        .HasColumnType("TEXT");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AttemptHistoryJson")
                        .HasColumnType("TEXT");

                    b.Property<long>("ChatId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("DequeuedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ErrorDetail")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxAttempts")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("NextRetryAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("SentAt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Severity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceEnvelopeJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<long?>("TelegramMessageId")
                        .HasColumnType("INTEGER");

                    b.HasKey("MessageId");

                    b.HasIndex("CorrelationId")
                        .HasDatabaseName("ix_outbox_correlation_id");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("ux_outbox_idempotency_key");

                    b.HasIndex("Status", "Severity", "CreatedAt")
                        .HasDatabaseName("ix_outbox_status_severity_created");

                    b.ToTable("outbox", (string)null);
                });

            modelBuilder.Entity("AgentSwarm.Messaging.Abstractions.OutboundMessageIdMapping", b =>
                {
                    b.Property<long>("ChatId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TelegramMessageId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<long>("SentAt")
                        .HasColumnType("INTEGER");

                    b.HasKey("ChatId", "TelegramMessageId");

                    b.HasIndex("CorrelationId")
                        .HasDatabaseName("ix_outbound_msgid_correlation_id");

                    b.ToTable("outbound_message_id_mappings", (string)null);
                });

            modelBuilder.Entity("AgentSwarm.Messaging.Core.OperatorBinding", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ChatType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OperatorAlias")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<long>("RegisteredAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Roles")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("TelegramChatId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TelegramUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkspaceId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TelegramUserId")
                        .HasDatabaseName("ix_operator_bindings_user");

                    b.HasIndex("OperatorAlias", "TenantId")
                        .IsUnique()
                        .HasDatabaseName("ux_operator_bindings_alias_tenant")
                        .HasFilter("\"IsActive\" = 1");

                    b.HasIndex("TelegramUserId", "TelegramChatId")
                        .HasDatabaseName("ix_operator_bindings_user_chat");

                    b.HasIndex("TelegramUserId", "TelegramChatId", "WorkspaceId")
                        .IsUnique()
                        .HasDatabaseName("ux_operator_bindings_user_chat_workspace");

                    b.ToTable("operator_bindings", (string)null);
                });

            modelBuilder.Entity("AgentSwarm.Messaging.Core.TaskOversight", b =>
                {
                    b.Property<string>("TaskId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<long>("AssignedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AssignedBy")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OperatorBindingId")
                        .HasColumnType("TEXT");

                    b.HasKey("TaskId");

                    b.HasIndex("OperatorBindingId")
                        .HasDatabaseName("ix_task_oversights_operator");

                    b.HasIndex("TaskId")
                        .HasDatabaseName("ix_task_oversights_task_id");

                    b.ToTable("task_oversights", (string)null);
                });

            modelBuilder.Entity("AgentSwarm.Messaging.Persistence.AuditLogEntry", b =>
                {
                    b.Property<Guid>("EntryId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ActionValue")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("AgentId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Comment")
                        .HasColumnType("TEXT");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Details")
                        .HasColumnType("TEXT");

                    b.Property<int>("EntryKind")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MessageId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("QuestionId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<long>("Timestamp")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("EntryId");

                    b.HasIndex("CorrelationId")
                        .HasDatabaseName("ix_audit_log_entries_correlation_id");

                    b.HasIndex("Timestamp")
                        .HasDatabaseName("ix_audit_log_entries_timestamp");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_audit_log_entries_user_id");

                    b.ToTable("audit_log_entries", (string)null);
                });

            modelBuilder.Entity("AgentSwarm.Messaging.Persistence.PendingQuestionRecord", b =>
                {
                    b.Property<string>("QuestionId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("AgentQuestionJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultActionId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultActionValue")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<long>("ExpiresAt")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("RespondentUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SelectedActionId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("SelectedActionValue")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<long>("StoredAt")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TelegramChatId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TelegramMessageId")
                        .HasColumnType("INTEGER");

                    b.HasKey("QuestionId");

                    b.HasIndex("DefaultActionId")
                        .HasDatabaseName("ix_pending_questions_default_action_id");

                    b.HasIndex("QuestionId")
                        .IsUnique()
                        .HasDatabaseName("ux_pending_questions_question_id");

                    b.HasIndex("Status", "ExpiresAt")
                        .HasDatabaseName("ix_pending_questions_status_expires_at");

                    b.HasIndex("TelegramChatId", "TelegramMessageId")
                        .HasDatabaseName("ix_pending_questions_chat_message");

                    b.HasIndex("TelegramChatId", "RespondentUserId", "Status")
                        .HasDatabaseName("ix_pending_questions_chat_user_status");

                    b.ToTable("pending_questions", (string)null);
                });

            modelBuilder.Entity("AgentSwarm.Messaging.Persistence.ProcessedEvent", b =>
                {
                    b.Property<string>("EventId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("event_id");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("DATETIME")
                        .HasColumnName("processed_at");

                    b.Property<DateTime>("ReservedAt")
                        .HasColumnType("DATETIME")
                        .HasColumnName("reserved_at");

                    b.HasKey("EventId");

                    b.HasIndex("ProcessedAt", "ReservedAt")
                        .HasDatabaseName("ix_processed_events_processed_reserved");

                    b.ToTable("processed_events", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
