namespace AgentSwarm.Messaging.Abstractions;

/// <summary>
/// Why a dead-lettered Telegram send ended up in the DLQ. Used by
/// <see cref="OutboundDeadLetterRecord"/> so the on-call operator can
/// distinguish a wedged Telegram backend (transient transport / 5xx)
/// from a legitimate flood-control rejection (429 budget exhausted)
/// from a never-retryable Bot API rejection (4xx other than 429 —
/// bad MarkdownV2, bot blocked by user, chat-not-found) without
/// parsing the underlying exception's message text.
/// </summary>
public enum OutboundFailureCategory
{
    /// <summary>
    /// Exhausted <see cref="int"/> retries against
    /// <c>HttpRequestException</c> / Telegram 5xx / request timeout.
    /// Operator action: check Telegram status page; verify network
    /// egress.
    /// </summary>
    TransientTransport,

    /// <summary>
    /// Exhausted retries against Telegram 429 flood-control. The bot
    /// is being throttled — either the global rate limiter is
    /// mis-tuned for the actual workload or a competing bot consumer
    /// is sharing the token. Operator action: tune
    /// <c>Telegram:RateLimits</c> or split the token.
    /// </summary>
    RateLimitExhausted,

    /// <summary>
    /// Iter-5 evaluator item 1 — Telegram Bot API rejected the send
    /// with a non-retryable status (4xx other than 429): malformed
    /// MarkdownV2 (HTTP 400 "can't parse entities"), bot blocked by
    /// the chat user (HTTP 403 "bot was blocked by the user"),
    /// chat-not-found (HTTP 400 "chat not found"), the operator
    /// revoked the bot's permissions on a group, or the bot token
    /// was invalidated. Retrying the same payload will never succeed
    /// — the only fix is content / configuration. Operator action:
    /// open the dead-letter row, inspect the LastErrorMessage, and
    /// EITHER re-render the connector payload (MarkdownV2) OR remove
    /// the chat from the operator allowlist (bot blocked). Distinct
    /// category so Stage 4.1's <c>OutboundQueueProcessor</c> can
    /// route these straight to DLQ instead of scheduling a delayed
    /// outbox-row retry.
    /// </summary>
    Permanent,
}

/// <summary>
/// Durable dead-letter record written by
/// <c>TelegramMessageSender</c> when a Telegram send exhausts its
/// in-sender retry budget. Iter-4 evaluator item 4 — the prior iter
/// only threw <c>TelegramSendFailedException</c> and optionally
/// emitted an alert; this record makes the dead-letter outcome
/// observable in the database so the operator audit trail survives a
/// worker restart and so Stage 4.1's <c>OutboundQueueProcessor</c>
/// can reconcile its outbox-row DLQ state against the sender's
/// dead-letter ledger when it lands.
/// </summary>
/// <remarks>
/// <para>
/// <b>Why a separate ledger and not the outbox row.</b> The Stage 4.1
/// outbox row (<see cref="OutboundMessage"/>) is the connector's view
/// of the send. The sender does not know the outbox <c>MessageId</c>
/// at retry-exhaustion time (the <see cref="IMessageSender"/> contract
/// takes <c>(chatId, text)</c> / <c>(chatId, envelope)</c> only). A
/// separate sender-owned ledger keyed by
/// (<see cref="ChatId"/>, <see cref="CorrelationId"/>) gives the
/// sender a place to persist the dead-letter outcome without coupling
/// to Stage 4.1's outbox-row primary key. When Stage 4.1 lands its
/// processor will JOIN this table on <see cref="CorrelationId"/> to
/// reconcile sender-side exhaustion with outbox-row status.
/// </para>
/// <para>
/// <b>CorrelationId guard.</b> Validated via
/// <see cref="CorrelationIdValidation.Require"/> at construction so a
/// dead-letter row cannot land with a blank trace id — the operator
/// pivot from alert into traces depends on a non-blank correlation
/// id.
/// </para>
/// </remarks>
public sealed record OutboundDeadLetterRecord
{
    private readonly string _correlationId = null!;

    /// <summary>
    /// Synthetic GUID primary key. Generated by the sender (or the
    /// store implementation) at insert time so the database does not
    /// have to coordinate identity values across concurrent senders.
    /// </summary>
    public required Guid DeadLetterId { get; init; }

    /// <summary>
    /// Telegram chat the failing send targeted. Indexed for the
    /// per-chat audit query "which sends to this chat have been
    /// dead-lettered in the last 24h".
    /// </summary>
    public required long ChatId { get; init; }

    /// <summary>
    /// Trace identifier of the failing send — the same id rendered in
    /// the message footer (when one made it onto the wire) and stored
    /// in the <see cref="IOutboundMessageIdIndex"/> for successful
    /// sends. Indexed for the trace-pivot operator query.
    /// </summary>
    public required string CorrelationId
    {
        get => _correlationId;
        init => _correlationId = CorrelationIdValidation.Require(value, nameof(CorrelationId));
    }

    /// <summary>
    /// Number of attempts consumed before the sender gave up. Equals
    /// the initial attempt + every retry. Records both 429-budget
    /// exhaustion and transient-error-budget exhaustion paths.
    /// </summary>
    public required int AttemptCount { get; init; }

    /// <summary>
    /// Discriminator for the failure mode — see
    /// <see cref="OutboundFailureCategory"/>. The on-call runbook
    /// branches on this field.
    /// </summary>
    public required OutboundFailureCategory FailureCategory { get; init; }

    /// <summary>
    /// Simple-name type of the last exception observed by the sender
    /// (e.g. <c>ApiRequestException</c>, <c>HttpRequestException</c>).
    /// Stored separately from <see cref="LastErrorMessage"/> so an
    /// operator query can GROUP BY type without parsing the free-form
    /// message.
    /// </summary>
    public required string LastErrorType { get; init; }

    /// <summary>
    /// Free-form text of the last exception's <c>Message</c>
    /// property. Bounded by EF Core mapping at 1024 chars; longer
    /// messages are truncated at write time.
    /// </summary>
    public required string LastErrorMessage { get; init; }

    /// <summary>
    /// UTC instant the sender gave up. Used for retention sweeps and
    /// for the "dead-lettered in the last 24h" operator screen.
    /// </summary>
    public required DateTimeOffset FailedAt { get; init; }
}
