namespace AgentSwarm.Messaging.Abstractions;

/// <summary>
/// Server-side state captured when an inbound command resolves to MORE
/// than one <c>OperatorBinding</c> for the same Telegram (user, chat) pair.
/// The Stage 2.2 pipeline (per <c>implementation-plan.md</c> §195–212)
/// stores one of these BEFORE emitting the multi-workspace inline-keyboard
/// prompt; the Stage 3.3 <c>CallbackQueryHandler</c> looks it up by the
/// short <see cref="Token"/> embedded in the tapped button's
/// <c>callback_data</c> and re-issues the original command bound to the
/// chosen workspace.
/// </summary>
/// <remarks>
/// <para>
/// <b>Why a server-side record instead of cramming everything into
/// <c>callback_data</c>.</b> Telegram caps <c>callback_data</c> at 64
/// UTF-8 bytes. Long commands such as <c>/handoff TASK-99 @op-2 because
/// the build is failing</c> easily blow that budget once the workspace
/// suffix is appended. Encoding only the short <see cref="Token"/> in
/// the button payload and parking the full original-command context
/// here on the server keeps the wire payload tiny while preserving
/// every field needed to re-issue the command verbatim. This closes
/// the iter-2 evaluator's "without a pending disambiguation/session
/// key or original command reference, the future callback handler has
/// no durable way to know which command the workspace selection
/// completes" finding.
/// </para>
/// <para>
/// <b>Token + index wire format (kept here, not on <c>InlineButton</c>).</b>
/// The pipeline generates <see cref="Token"/> from a cryptographically
/// random byte source and projects it to printable ASCII. The full
/// <c>callback_data</c> wire format is
/// <c>ws:&lt;token&gt;:&lt;index&gt;</c> where <c>ws:</c> is
/// <see cref="WorkspaceCallbackDataPrefix"/> and <c>&lt;index&gt;</c>
/// is the 0-based position into <see cref="CandidateWorkspaceIds"/>
/// (NOT the workspace id itself). Stage 3.3 splits on the second
/// colon to recover the token (for store lookup) and the integer
/// index (for resolving the chosen workspace via
/// <c>CandidateWorkspaceIds[index]</c>). Encoding the index instead
/// of the workspace id makes the wire format robust against arbitrary
/// workspace identifiers — long IDs cannot exceed Telegram's 64-byte
/// <c>callback_data</c> cap, and IDs containing the structural
/// separator <c>:</c> cannot corrupt parsing — addressing the iter-3
/// evaluator's robustness pin.
/// </para>
/// <para>
/// <b>Single-use semantics.</b>
/// <see cref="IPendingDisambiguationStore.TakeAsync"/> is a
/// remove-on-read operation: once a callback is consumed, the entry is
/// gone, so a malicious user replaying the same callback cannot
/// re-trigger the original command. <see cref="ExpiresAt"/> bounds the
/// staleness window for never-tapped prompts.
/// </para>
/// </remarks>
public sealed record PendingDisambiguation
{
    /// <summary>
    /// Maximum length in characters of <see cref="Token"/>. Bounded so
    /// the full <c>callback_data</c> (<c>ws:</c> + token + <c>:</c> +
    /// 0-based index) fits inside Telegram's 64-byte cap with ample
    /// headroom for any practical binding count.
    /// </summary>
    public const int MaxTokenLength = 16;

    /// <summary>Wire prefix for workspace-selection callbacks.</summary>
    public const string WorkspaceCallbackDataPrefix = "ws:";

    /// <summary>
    /// Short, printable-ASCII opaque handle embedded in each
    /// inline-keyboard button's <c>callback_data</c>. Generated by the
    /// pipeline; must be unique within the active disambiguation
    /// window. Stage 3.3 uses this as the
    /// <see cref="IPendingDisambiguationStore.TakeAsync"/> lookup key.
    /// </summary>
    public required string Token { get; init; }

    /// <summary>
    /// Original raw command text the operator typed (verbatim, INCLUDING
    /// the leading <c>/</c> and any arguments). Stage 3.3 re-feeds this
    /// through <see cref="ICommandParser"/> after the workspace is chosen,
    /// guaranteeing the disambiguated command is byte-identical to what
    /// the operator originally sent.
    /// </summary>
    public required string OriginalRawCommand { get; init; }

    /// <summary>
    /// Trace correlation ID from the original
    /// <see cref="MessengerEvent.CorrelationId"/>. Re-used on the
    /// disambiguated re-issue so the audit trail (Stage 5.3) and any
    /// structured log query can stitch the prompt and the eventual
    /// command execution into one trace.
    /// </summary>
    public required string CorrelationId { get; init; }

    /// <summary>Original Telegram user ID that issued the command.</summary>
    public required string TelegramUserId { get; init; }

    /// <summary>Original Telegram chat ID where the command arrived.</summary>
    public required string TelegramChatId { get; init; }

    /// <summary>
    /// Workspace identifiers the operator may pick from, in the SAME
    /// order the inline-keyboard buttons were rendered. The wire format
    /// (<c>ws:&lt;token&gt;:&lt;index&gt;</c>) carries only the integer
    /// index, so this list IS the authoritative source for resolving
    /// the chosen workspace at the Stage 3.3 callback. A non-numeric or
    /// out-of-range index in a tapped callback indicates either a
    /// hostile payload or a stale prompt that survived a server
    /// restart; Stage 3.3 must reject both rather than fall back to a
    /// default workspace.
    /// </summary>
    public required IReadOnlyList<string> CandidateWorkspaceIds { get; init; }

    /// <summary>
    /// Wall-clock timestamp the disambiguation entry was stored
    /// (informational; useful for log correlation).
    /// </summary>
    public required DateTimeOffset CreatedAt { get; init; }

    /// <summary>
    /// Wall-clock timestamp after which the entry is considered stale.
    /// <see cref="IPendingDisambiguationStore.PurgeExpiredAsync"/> drops
    /// entries past this point; <see cref="IPendingDisambiguationStore.TakeAsync"/>
    /// returns <c>null</c> for an expired entry even before purge.
    /// </summary>
    public required DateTimeOffset ExpiresAt { get; init; }
}
