// <auto-generated />
using System;
using AgentSwarm.Messaging.Teams.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AgentSwarm.Messaging.Teams.EntityFrameworkCore.Migrations
{
    [DbContext(typeof(TeamsConversationReferenceDbContext))]
    [Migration("20260515051028_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AgentSwarm.Messaging.Teams.EntityFrameworkCore.ConversationReferenceEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("AadObjectId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("BotId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("ChannelId")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("ConversationId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("ConversationJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DeactivatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DeactivationReason")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("InternalUserId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("ServiceUrl")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("TeamId")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_ConversationReferences_IsActive")
                        .HasFilter("\"IsActive\" = 1");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("IX_ConversationReferences_TenantId");

                    b.HasIndex("AadObjectId", "TenantId")
                        .IsUnique()
                        .HasDatabaseName("IX_ConversationReferences_AadObjectId_TenantId")
                        .HasFilter("\"AadObjectId\" IS NOT NULL");

                    b.HasIndex("ChannelId", "TenantId")
                        .IsUnique()
                        .HasDatabaseName("IX_ConversationReferences_ChannelId_TenantId")
                        .HasFilter("\"ChannelId\" IS NOT NULL");

                    b.HasIndex("InternalUserId", "TenantId")
                        .HasDatabaseName("IX_ConversationReferences_InternalUserId_TenantId")
                        .HasFilter("\"InternalUserId\" IS NOT NULL");

                    b.ToTable("ConversationReferences", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
