namespace AgentSwarm.Messaging.Persistence;

using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

/// <summary>
/// Persistent record of an inbound Discord interaction (slash command, button,
/// select menu, modal submit, etc.).
///
/// This entity is the inbox-side idempotency anchor for the Discord connector.
/// It is written when an interaction is first received, then updated as the
/// connector processes it. The lifecycle is:
///
///   Received -> Processing -> Completed
///                          -> Failed (terminal; may be retried by recovery sweep)
///
/// The connector's restart-recovery loop (FR-005) and parallel worker pool
/// (FR-007: 100+ concurrent agents, 0 message loss) both may attempt to claim
/// rows in Received/Processing state. To prevent two workers from silently
/// clobbering each other's status update (which EF would otherwise issue as an
/// unconditional UPDATE ... WHERE Id = @id), this entity carries a
/// <see cref="RowVersion"/> concurrency token. EF Core appends the token to the
/// WHERE clause and raises <see cref="Microsoft.EntityFrameworkCore.DbUpdateConcurrencyException"/>
/// when the underlying row has moved on, allowing the losing worker to re-read
/// and re-evaluate instead of overwriting committed state.
/// </summary>
public class DiscordInteractionRecord
{
    /// <summary>
    /// Surrogate primary key. Generated by the database.
    /// </summary>
    [Key]
    public Guid Id { get; set; }

    /// <summary>
    /// Discord's interaction snowflake. Used together with
    /// <see cref="InteractionToken"/> for duplicate suppression of webhook
    /// replays (Discord may redeliver an interaction if the gateway ACK is
    /// lost). A unique index is configured on this column.
    /// </summary>
    [Required]
    [MaxLength(64)]
    public string InteractionId { get; set; } = string.Empty;

    /// <summary>
    /// Discord interaction token, retained for follow-up REST calls.
    /// Never logged.
    /// </summary>
    [Required]
    [MaxLength(256)]
    public string InteractionToken { get; set; } = string.Empty;

    /// <summary>
    /// Discord interaction kind: ApplicationCommand, MessageComponent,
    /// ModalSubmit, etc. Stored as the Discord numeric value so the catalog
    /// stays stable across Discord.Net upgrades.
    /// </summary>
    public int InteractionType { get; set; }

    /// <summary>Discord guild (server) snowflake. Required for FR-006 tenant validation.</summary>
    [Required]
    [MaxLength(64)]
    public string GuildId { get; set; } = string.Empty;

    /// <summary>Discord channel snowflake.</summary>
    [Required]
    [MaxLength(64)]
    public string ChannelId { get; set; } = string.Empty;

    /// <summary>Discord user snowflake of the human who triggered the interaction.</summary>
    [Required]
    [MaxLength(64)]
    public string ExternalUserId { get; set; } = string.Empty;

    /// <summary>
    /// External message id associated with the interaction (for component
    /// interactions that reference a prior bot message). Null for slash
    /// commands invoked outside a message context.
    /// </summary>
    [MaxLength(64)]
    public string? ExternalMessageId { get; set; }

    /// <summary>End-to-end correlation id (FR-004). Always populated.</summary>
    [Required]
    [MaxLength(128)]
    public string CorrelationId { get; set; } = string.Empty;

    /// <summary>Agent identity this interaction is routed to (FR-004).</summary>
    [MaxLength(128)]
    public string? AgentId { get; set; }

    /// <summary>Work-item identity this interaction is associated with (FR-004).</summary>
    [MaxLength(128)]
    public string? TaskId { get; set; }

    /// <summary>Conversation/thread id this interaction belongs to (FR-004).</summary>
    [MaxLength(128)]
    public string? ConversationId { get; set; }

    /// <summary>
    /// Lifecycle state used to drive idempotent processing and restart recovery.
    /// Updates to this column MUST flow through EF's change tracker so the
    /// <see cref="RowVersion"/> guard takes effect.
    /// </summary>
    [Required]
    public IdempotencyStatus IdempotencyStatus { get; set; } = IdempotencyStatus.Received;

    /// <summary>Raw interaction payload (JSON) for replay and audit (FR-006).</summary>
    public string? Payload { get; set; }

    /// <summary>Failure detail when <see cref="IdempotencyStatus"/> is Failed.</summary>
    public string? ErrorMessage { get; set; }

    /// <summary>Number of times processing has been attempted (FR-005 retry policy).</summary>
    public int RetryCount { get; set; }

    /// <summary>UTC instant the interaction was first persisted (FR-004 Timestamp).</summary>
    [Required]
    public DateTimeOffset ReceivedAt { get; set; }

    /// <summary>UTC instant a worker most recently claimed the row for processing.</summary>
    public DateTimeOffset? ProcessingStartedAt { get; set; }

    /// <summary>UTC instant processing reached a terminal state (Completed or Failed).</summary>
    public DateTimeOffset? CompletedAt { get; set; }

    /// <summary>
    /// Optimistic-concurrency token. Provider-mapped to a SQL Server
    /// <c>rowversion</c>/<c>timestamp</c> column via <see cref="TimestampAttribute"/>
    /// and configured as <c>IsRowVersion()</c> in
    /// <c>DiscordInteractionRecordConfiguration</c> for non-SQL-Server providers
    /// (e.g. Sqlite test doubles) so the same guard applies everywhere.
    ///
    /// Required to satisfy FR-005 (connector restart recovery) and FR-007
    /// (0 tolerated message loss with 100+ concurrent agents): two workers or
    /// a worker plus a recovery sweep that both pick up the same
    /// Received/Processing row will have one <c>SaveChangesAsync</c> succeed
    /// and the other raise <see cref="Microsoft.EntityFrameworkCore.DbUpdateConcurrencyException"/>,
    /// preventing a silent lost-update.
    /// </summary>
    [Timestamp]
    public byte[]? RowVersion { get; set; }
}
